import { Btn, Flex } from '../../src'

export default function AllBtnDemo () {
  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      gap: 8,
    }}
    >
      <Flex gap="8px">
        <Btn
          fill
          label="Fill"
        />
        <Btn
          text
          label="Text"
        />
        <Btn
          contrast
          label="Contrast"
        />
      </Flex>
      <div style={{ flexWrap: 'wrap', display: 'flex', gap: 8 }}>
        <Btn
          fill
          color="primary"
          label="Primary"
        />
        <Btn
          fill
          color="success"
          label="Success"
        />
        <Btn
          fill
          color="danger"
          label="Danger"
        />
        <Btn
          fill
          color="warning"
          label="Warning"
        />
        <Btn
          fill
          label="Default"
        />
      </div>
      <div style={{ flexWrap: 'wrap', display: 'flex', gap: 8 }}>
        <Btn
          text
          color="primary"
          label="Primary"
        />
        <Btn
          text
          color="success"
          label="Success"
        />
        <Btn
          text
          color="danger"
          label="Danger"
        />
        <Btn
          text
          color="warning"
          label="Warning"
        />
        <Btn
          text
          color="default"
          label="Default"
        />
      </div>
      <div style={{ flexWrap: 'wrap', display: 'flex', gap: 8 }}>
        <Btn
          contrast
          color="primary"
          label="Primary"
        />
        <Btn
          contrast
          color="success"
          label="Success"
        />
        <Btn
          contrast
          color="danger"
          label="Danger"
        />
        <Btn
          contrast
          color="warning"
          label="Warning"
        />
        <Btn
          contrast
          label="Default"
        />
      </div>
      <div style={{ flexWrap: 'wrap', display: 'flex', gap: 8 }}>
        <Btn
          border
          dash
          text
          color="primary"
          label="Primary"
        />
        <Btn
          border
          dash
          text
          color="success"
          label="Success"
        />
        <Btn
          border
          dash
          text
          color="danger"
          label="Danger"
        />
        <Btn
          border
          dash
          text
          color="warning"
          label="Warning"
        />
        <Btn
          border
          dash
          text
          label="Default"
        />
      </div>
      <div style={{ flexWrap: 'wrap', display: 'flex', gap: 8 }}>
        <Btn
          dash
          disabled
          color="primary"
          label="Primary"
        />
        <Btn
          dash
          disabled
          color="success"
          label="Success"
        />
        <Btn
          dash
          disabled
          color="danger"
          label="Danger"
        />
        <Btn
          dash
          disabled
          color="warning"
          label="Warning"
        />
        <Btn
          dash
          disabled
          label="Default"
        />
      </div>
    </div>
  )
}
